repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (lint)
        entry: ruff check --fix
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        pass_filenames: false
        args: ["src"]
      - id: bandit
        name: bandit
        entry: bandit -c pyproject.toml -r src
        language: system
        pass_filenames: false
      - id: pip-audit
        name: pip-audit
        entry: pip-audit --strict --skip-editable .
        language: system
        pass_filenames: false
      - id: coverage-pytest
        name: coverage run -m pytest
        entry: bash -c "coverage run -m pytest && coverage report --fail-under=85"
        language: system
        pass_filenames: false
