name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Ruff lint
        run: ruff check .

      - name: Mypy (strict)
        run: mypy --strict src/

      - name: Bandit security scan
        run: bandit -c pyproject.toml -r src/

      - name: pip-audit
        run: pip-audit --strict --skip-editable .

      - name: Pytest with coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=85
